language: php

branches:
  only:
    - master
    - develop

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer install --dev --prefer-source

script: ./vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm